#!/bin/bash

# Run the blackbox exporter
./blackbox_exporter &

# Wait for 100ms for the exporter to initialize
sleep 0.1

while true
do
    HEADERS="$(mktemp)"

    # 1. Retrieve the information of the invocation, including headers and the payload of the event.
    #    The headers will be stored in the file created when running the mktemp command.
    EVENT_DATA=$(curl -sS -LD "$HEADERS" "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

    # 2. Parse the event, retrieving the url to be probed
    TARGET=$(echo "$EVENT_DATA" | grep -o '"body":"[^"]*' | grep -o '[^"]*$' | base64 --decode)

    # 3. Retrieve the response from blackbox exporter
    RESPONSE=$(curl "localhost:9115/probe?target=$TARGET&module=http_2xx")

    # 4. From the file, get the request ID, so we are able to successfully comunicate the response
    REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

    # 5. Send the response from the probing back to the caller
    curl "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response" -d "$RESPONSE"
done
